AWSTemplateFormatVersion: "2010-09-09"
Description: Spdataservice API-Gateway Set up.

Parameters:
  Service:
    Type: String
    Default: spdataservice
  environment:
    Type: String
    Default: dev
  envId:
    AllowedValues: ["spds01", "spds02"]
    Type: String
    Default: spds01

  #########################################################################################
  # ?????????
  #########################################################################################
Resources:
  #################################################
  # API Gateway ????????
  #################################################
  # CrpfInternalApiApigatewayLogGroup:
  #   Type: AWS::Logs::LogGroup
  #   Properties:
  #     LogGroupName: !Sub /aws/apigateway/logs/${envId}-${environment}-${Service}-internalapi-apigateway
  #     Tags:
  #       - Key: Name
  #         Value: !Sub /aws/apigateway/logs/${envId}-${environment}-${Service}-internalapi-apigateway
  #       - Key: Service
  #         Value: !Ref Service
  #       - Key: Environment
  #         Value: !Ref Environment

  ###############################
  #VPClink
  ###############################
  VpcLink:
    Type: AWS::ApiGateway::VpcLink
    Properties:
      Name: !Sub ${envId}-${environment}-${Service}-vpclink
      TargetArns:
        - Fn::ImportValue: !Sub ${envId}-${environment}-ALB
      Tags:
        - Key: Name
          Value: !Sub ${envId}-${environment}-${Service}-vpclink
        - Key: Service
          Value: !Ref Service
        - Key: Environment
          Value: !Ref environment

  ####################################################################
  # APIKey?? ?APIKey???SecretManager???????
  ####################################################################
  # Internal APIKey
  # InternalApiKey:
  #   Type: AWS::ApiGateway::ApiKey
  #   Properties:
  #     # Name: CrpfApiApiKey
  #     Name: !Sub ${envId}-${environment}-${Service}-internalapi-apikey
  #     Description: CloudFormation API Key for spdataservice internal From SecretsManager
  #     Enabled: True
  #     Value:
  #       !Join [
  #         "",
  #         [
  #           "{{resolve:secretsmanager:",
  #           !ImportValue SecretForInternalApiOutputFromSecretsManager,
  #           ":SecretString:password}}",
  #         ],
  #       ]
  #     Tags:
  #       - Key: Name
  #         Value: !Sub ${envId}-${environment}-${Service}-internalapi-apikey
  #       - Key: Service
  #         Value: !Ref Service
  #       - Key: Environment
  #         Value: !Ref environment

  # ????APIKey
  # ExternalApiKey:
  #   Type: AWS::ApiGateway::ApiKey
  #   Properties:
  #     # Name: ApiKey
  #     Name: !Sub ${envId}-${environment}-${Service}-externalapi-apikey
  #     Description: CloudFormation API Key for spdataservice External From SecretsManager
  #     Enabled: True
  #     Value:
  #       !Join [
  #         "",
  #         [
  #           "{{resolve:secretsmanager:",
  #           !ImportValue SecretForExternalApiOutputFromSecretsManager,
  #           ":SecretString:password}}",
  #         ],
  #       ]
  #     Tags:
  #       - Key: Name
  #         Value: !Sub ${envId}-${environment}-${Service}-externalapi-apikey
  #       - Key: Service
  #         Value: !Ref Service
  #       - Key: Environment
  #         Value: !Ref environment

  ####################################################################
  # ApiGateway UsagePlan
  ####################################################################
  # ??????????
  # InternalApiUsagePlan:
  #   Type: "AWS::ApiGateway::UsagePlan"
  #   Properties:
  #     Description: !Sub ${envId}-${environment}-${Service}-internalapi-usageplan
  #     # ?????????????????????
  #     # Quota:
  #     #   Limit: 2000
  #     #   Period: DAY
  #     # Throttle:
  #     #   BurstLimit: 100
  #     #   RateLimit: 100
  #     UsagePlanName: !Sub ${envId}-${environment}-${Service}-internalapi-usageplan
  #     Tags:
  #       - Key: Name
  #         Value: !Sub ${envId}-${environment}-${Service}-internalapi-usageplan
  #       - Key: Service
  #         Value: !Ref Service
  #       - Key: Environment
  #         Value: !Ref environment

  # ??????????
  # ExternalApiUsagePlan:
  #   Type: "AWS::ApiGateway::UsagePlan"
  #   Properties:
  #     Description: !Sub ${envId}-${environment}-${Service}-externalapi-usageplan
  #     # ?????????????????????
  #     # Quota:
  #     #   Limit: 2000
  #     #   Period: DAY
  #     # Throttle:
  #     #   BurstLimit: 100
  #     #   RateLimit: 100
  #     UsagePlanName: !Sub ${envId}-${environment}-${Service}-externalapi-usageplan
  #     Tags:
  #       - Key: Name
  #         Value: !Sub ${envId}-${environment}-${Service}-externalapi-usageplan
  #       - Key: Service
  #         Value: !Ref Service
  #       - Key: Environment
  #         Value: !Ref environment
  ####################################################################
  # ApiGateway UsagePlanKey
  ####################################################################
  # 
  # InternalApiUsagePlanKey:
  #   Type: "AWS::ApiGateway::UsagePlanKey"
  #   Properties:
  #     KeyId: !Ref InternalApiKey
  #     KeyType: API_KEY
  #     UsagePlanId: !Ref InternalApiUsagePlan

  # # 
  # ExternalApiUsagePlanKey:
  #   Type: "AWS::ApiGateway::UsagePlanKey"
  #   Properties:
  #     KeyId: !Ref ExternalApiKey
  #     KeyType: API_KEY
  #     UsagePlanId: !Ref ExternalApiUsagePlan