server:
    port: 8080

logging:
    level:
        root: ERROR
        org:
            springframework:
                web: ERROR
        com:
            iibc:
                spdataservice: TRACE

spring:
    datasource:
        url: jdbc:mysql://${MYSQL_HOST:localhost}:3306/appdb
        username: appuser
        password: pass
        driver-class-name: com.mysql.cj.jdbc.Driver
    thymeleaf:
        cache: false
        
okta:
  oauth2:
    # Replace with the domain of your Auth0 tenant.
    issuer: https://dev-zawminhtoon.jp.auth0.com/
    # Replace with the API Identifier for your Auth0 API.
    audience: https://test-api
    client-id: Qcz08WqWkdQKlxIeDFofTtluuLbjZ1rf
    client-secret: KwriXi2mPlv56WdlUpAYZv58bsDzMdal6BBNnOgDBM0g6bIkaXRr7ibr4QepXa2J
    scopes: 
      - openid
      - profile
      - email
      - offline_access