AWSTemplateFormatVersion: 2010-09-09
Description:
  Cafe(Cafeteria Plan) - CloudFront  Set up.

  #########################################################################################
  # ??????????
  #########################################################################################

Parameters:
  ###################################################################
  # ???????
  ###################################################################

  # # ?????ID
  # AccountId:
  #   Type: String
  # ????????
  Service:
    Type: String
  # ????
  Environment:
    Type: String
  # ?????????????ACM????cloudfront??
  VirginiaAcm:
    Type: String
  # Web  Cloudfront?????????
  # ????????????????????????CloudFormation??????????(CloudFormation???)
  WebCloudfrontCustomDnsName:
    Type: String
  # ALB?????????
  WebAlbCustomDnsName:
    Type: String
  # ????
  environment:
    Type: String
  # ??ID bo01
  envId:
    AllowedValues: ["bo01", "bo02"]
    Type: String

###################################################################
# Input Parameters
###################################################################

Resources:
  ###################################################################
  #  CloudFront - Object Access Identity
  ###################################################################

  # CafeWebCloudFrontOriginAccessIdentity:
  #   Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
  #   Properties:
  #     CloudFrontOriginAccessIdentityConfig:
  #       Comment: !Sub "access-identity-${envId}-${environment}-${Service}-s3-web-${AWS::AccountId}.s3.${AWS::Region}.amazonaws.com"

  # ###################################################################
  # #  S3 - BucketPolicy   # CloudFront?????????
  # ###################################################################

## 3??????????????????????????????????????????????
  # CafeWebCloudFrontBucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     Bucket: !Sub ${envId}-${environment}-${Service}-s3-web-${AWS::AccountId}
  #     PolicyDocument:
  #       Statement:
  #         - Action: s3:GetObject
  #           Effect: Allow
  #           Resource: !Sub arn:aws:s3:::${envId}-${environment}-${Service}-s3-web-${AWS::AccountId}/*
  #           Principal:
  #             AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${CafeWebCloudFrontOriginAccessIdentity}

  ###################################################################
  #  CloudFront - Distribution
  ###################################################################
  CafeWebDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        HttpVersion: http2
        Origins:
          # # Origin?S3???
          # - Id: S3Origin
          #   DomainName: !Sub ${envId}-${environment}-${Service}-s3-web-${AWS::AccountId}.s3.${AWS::Region}.amazonaws.com
          #   S3OriginConfig:
          #     OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${CafeWebCloudFrontOriginAccessIdentity}"
          # Origin?ALB???
          - Id: AlbOrigin
            # Web-ALB????????????
            DomainName: !Ref WebAlbCustomDnsName
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols: ["TLSv1.2"]
        Enabled: true
        Comment: Cafe Web (??) Distribution
        # DefaultRootObject: /
        #S3??????????
        Logging:
          #IncludeCookies: 'true'
          Bucket: !ImportValue CafeS3LogDomainNameOutput
          Prefix: !Sub RawLogs/cloudfront/${envId}-${environment}-${Service}-web-cloudfront
        #DefaultCacheBehavior???
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          TargetOriginId: AlbOrigin
          ForwardedValues:
            Headers:
              - Host
            QueryString: true
            Cookies:
              Forward: all
          ViewerProtocolPolicy: redirect-to-https
          SmoothStreaming: true
          #?????????????TTL?0????????
          MinTTL: 0
          DefaultTTL: 0
          MaxTTL: 0
        #CacheBehavior???(ALB)
        # CacheBehaviors:
          # - AllowedMethods:
          #     - DELETE
          #     - GET
          #     - HEAD
          #     - OPTIONS
          #     - PATCH
          #     - POST
          #     - PUT
          #   TargetOriginId: AlbOrigin
          #   ForwardedValues:
          #     Headers:
          #       - Host
          #     QueryString: true
          #     Cookies:
          #       Forward: all
          #   ViewerProtocolPolicy: redirect-to-https
          #   # ?????????????TTL?0????????
          #   MinTTL: 0
          #   DefaultTTL: 0
          #   MaxTTL: 0
          #CacheBehavior???(S3)
          # - AllowedMethods:
          #     - DELETE
          #     - GET
          #     - HEAD
          #     - OPTIONS
          #     - PATCH
          #     - POST
          #     - PUT
          #   TargetOriginId: S3Origin
          #   ForwardedValues:
          #     QueryString: false
          #     Cookies:
          #       Forward: none
          #   ViewerProtocolPolicy: https-only
          #   PathPattern: /web/*
          #   # ?????????????TTL?0????????
          #   MinTTL: 0
          #   DefaultTTL: 0
          #   MaxTTL: 0
        # 50X????????Sorry???(503)??????????????
        CustomErrorResponses:
          - ErrorCode: 500
            ResponsePagePath: /sorry.html
            ResponseCode: 503
            ErrorCachingMinTTL: 0
          - ErrorCode: 501
            ResponsePagePath: /sorry.html
            ResponseCode: 503
            ErrorCachingMinTTL: 0
          - ErrorCode: 502
            ResponsePagePath: /sorry.html
            ResponseCode: 503
            ErrorCachingMinTTL: 0
          - ErrorCode: 503
            ResponsePagePath: /sorry.html
            ResponseCode: 503
            ErrorCachingMinTTL: 0
          - ErrorCode: 504
            ResponsePagePath: /sorry.html
            ResponseCode: 503
            ErrorCachingMinTTL: 0
        PriceClass: PriceClass_All
        # ??????????? (us-east-1) ????????????????????
        ViewerCertificate:
          AcmCertificateArn: !Ref VirginiaAcm
          MinimumProtocolVersion: "TLSv1.2_2021"
          SslSupportMethod: "sni-only"
        ###################################################################
        # ????????????????????????CloudFormation??????????(CloudFormation???)
        ###################################################################
        Aliases:
          - !Ref WebCloudfrontCustomDnsName
      Tags:
        - Key: Name
          Value: !Sub ${envId}-${environment}-${Service}-web-cloudfront
        - Key: Service
          Value: !Ref Service
        - Key: Environment
          Value: !Ref Environment

# Outputs:
#   # ????????? OAI Output
#   CafeWebCloudFrontOriginAccessIdentityOutput:
#     Value: !Ref CafeWebCloudFrontOriginAccessIdentity
#     Export:
#       Name: CafeWebCloudFrontOriginAccessIdentityOutput          