AWSTemplateFormatVersion: 2010-09-09
Description:
  MnppPpgm - CloudFront Set up.

  #########################################################################################
  # ??????????
  #########################################################################################

Parameters:
  ###################################################################
  # ???????
  ###################################################################

  # # ?????ID
  # AccountId:
  #   Type: String
  # ????????
  Service:
    Type: String
    Default: mnpp-ppgm
  # ????
  Environment:
    Type: String
    Default: Dev
  # ???? ???
  environment:
    Type: String
    Default: dev
  # ??ID
  envId:
    AllowedValues: ["bo01", "bo02", "bo03"]
    Type: String
    Default: bo02
  # ?????????????ACM????cloudfront??
  VirginiaAcm:
    Type: String
    Default: arn:aws:acm:us-east-1:000323109652:certificate/0e08b3f1-80b1-4236-b225-fb183f76a4f3
  # Web Admin Cloudfront?????????
  WebAdminCloudfrontCustomDnsName:
    Type: String
    Default: ppgm.mnpp.b-sysi.com
  # ALB?????????
  WebAdminAlbCustomDnsName:
    Type: String
    Default: admin-alb.ppgm.mnpp.b-sysi.com

###################################################################
# Input Parameters
###################################################################

Resources:
  ###################################################################
  #  CloudFront - Object Access Identity
  ###################################################################

  # MnppPpgmWebAdminCloudFrontOriginAccessIdentity:
  #   Type: AWS::CloudFront::CloudFrontOriginAccessIdentity
  #   Properties:
  #     CloudFrontOriginAccessIdentityConfig:
  #       Comment: !Sub "access-identity-${envId}-${environment}-${Service}-s3-web-${AWS::AccountId}.s3.${AWS::Region}.amazonaws.com"

  # ###################################################################
  # #  S3 - BucketPolicy   # CloudFront?????????
  # ###################################################################

  ## 3??????????????????????????????????????????????????????????
  # MnppPpgmWebAdminCloudFrontBucketPolicy:
  #   Type: AWS::S3::BucketPolicy
  #   Properties:
  #     Bucket: !Sub ${envId}-${environment}-${Service}-s3-web-${AWS::AccountId}
  #     PolicyDocument:
  #       Statement:
  #         - Action: s3:GetObject
  #           Effect: Allow
  #           Resource: !Sub arn:aws:s3:::${envId}-${environment}-${Service}-s3-web-${AWS::AccountId}/*
  #           Principal:
  #             AWS: !Sub arn:aws:iam::cloudfront:user/CloudFront Origin Access Identity ${MnppPpgmWebAdminCloudFrontOriginAccessIdentity}

  ###################################################################
  #  CloudFront - Distribution
  ###################################################################
  MnppPpgmWebAdminDistribution:
    Type: AWS::CloudFront::Distribution
    Properties:
      DistributionConfig:
        HttpVersion: http2
        Origins:
          # # Origin?S3???
          # - Id: S3Origin
          #   DomainName: !Sub ${envId}-${environment}-${Service}-s3-web-${AWS::AccountId}.s3.${AWS::Region}.amazonaws.com
          #   S3OriginConfig:
          #     OriginAccessIdentity: !Sub "origin-access-identity/cloudfront/${MnppPpgmWebAdminCloudFrontOriginAccessIdentity}"
          # Origin?ALB???
          - Id: AlbOrigin
            # Web-Admin-ALB????????????
            DomainName: !Ref WebAdminAlbCustomDnsName
            CustomOriginConfig:
              HTTPSPort: 443
              OriginProtocolPolicy: https-only
              OriginSSLProtocols: ["TLSv1.2"]
        Enabled: true
        Comment: MnppPpgm Web Admin (operator) Distribution
        # DefaultRootObject: /
        #S3??????????
        Logging:
          #IncludeCookies: 'true'
          Bucket: !ImportValue MnppPpgmS3LogDomainNameOutput
          Prefix: !Sub RawLogs/cloudfront/${envId}-${environment}-${Service}-web-admin-cloudfront
        #DefaultCacheBehavior???
        DefaultCacheBehavior:
          AllowedMethods:
            - DELETE
            - GET
            - HEAD
            - OPTIONS
            - PATCH
            - POST
            - PUT
          TargetOriginId: AlbOrigin
          ForwardedValues:
            Headers:
              - Host
            QueryString: true
            Cookies:
              Forward: all
          ViewerProtocolPolicy: redirect-to-https
          SmoothStreaming: true
          #?????????????TTL?0????????
          MinTTL: 0
          DefaultTTL: 0
          MaxTTL: 0
        #CacheBehavior???(ALB)
        # CacheBehaviors:
        # - AllowedMethods:
        #     - DELETE
        #     - GET
        #     - HEAD
        #     - OPTIONS
        #     - PATCH
        #     - POST
        #     - PUT
        #   TargetOriginId: AlbOrigin
        #   ForwardedValues:
        #     Headers:
        #       - Host
        #     QueryString: true
        #     Cookies:
        #       Forward: all
        #   ViewerProtocolPolicy: redirect-to-https
        #   PathPattern: /web/admin*
        #   # ?????????????TTL?0????????
        #   MinTTL: 0
        #   DefaultTTL: 0
        #   MaxTTL: 0
        #CacheBehavior???(S3)
        # - AllowedMethods:
        #     - DELETE
        #     - GET
        #     - HEAD
        #     - OPTIONS
        #     - PATCH
        #     - POST
        #     - PUT
        #   TargetOriginId: S3Origin
        #   ForwardedValues:
        #     QueryString: false
        #     Cookies:
        #       Forward: none
        #   ViewerProtocolPolicy: https-only
        #   PathPattern: /web/*
        #   # ?????????????TTL?0????????
        #   MinTTL: 0
        #   DefaultTTL: 0
        #   MaxTTL: 0
        # 50X????????Sorry???(503)??????????????
        CustomErrorResponses:
          - ErrorCode: 500
            ResponsePagePath: /sorry.html
            ResponseCode: 503
            ErrorCachingMinTTL: 0
          - ErrorCode: 501
            ResponsePagePath: /sorry.html
            ResponseCode: 503
            ErrorCachingMinTTL: 0
          - ErrorCode: 502
            ResponsePagePath: /sorry.html
            ResponseCode: 503
            ErrorCachingMinTTL: 0
          - ErrorCode: 503
            ResponsePagePath: /sorry.html
            ResponseCode: 503
            ErrorCachingMinTTL: 0
          - ErrorCode: 504
            ResponsePagePath: /sorry.html
            ResponseCode: 503
            ErrorCachingMinTTL: 0
        PriceClass: PriceClass_All
        ###################################################################
        # ACM???????????????????
        ###################################################################
        # ??????????? (us-east-1) ????????????????????
        ViewerCertificate:
          AcmCertificateArn: !Ref VirginiaAcm
          MinimumProtocolVersion: "TLSv1.2_2021"
          SslSupportMethod: "sni-only"
        ###################################################################
        # Cloudfront?????????????????????????
        ###################################################################
        Aliases:
          - !Ref WebAdminCloudfrontCustomDnsName
      Tags:
        - Key: Name
          Value: !Sub ${envId}-${environment}-${Service}-web-admin-cloudfront
        - Key: Service
          Value: !Ref Service
        - Key: Environment
          Value: !Ref Environment
        - Key: CmBillingGroup
          Value: !Ref Service
# Outputs:
#   # ????????? OAI Output
#   MnppPpgmWebAdminCloudFrontOriginAccessIdentityOutput:
#     Value: !Ref MnppPpgmWebAdminCloudFrontOriginAccessIdentity
#     Export:
#       Name: MnppPpgmWebAdminCloudFrontOriginAccessIdentityOutput
