AWSTemplateFormatVersion: 2010-09-09
Description: "VPCテンプレート"

Parameters:
  PJPrefix:
    Type: String

  AvailabilityZone1:
    Type: String

  VpcCidrBlock:
    Description: "VPCのCIDRブロック"
    Type: String
    Default: "10.0.0.0/16"

  VpcSubnetCidr:
    Description: "VPC SubnetのCIDRブロック"
    Type: String
    Default: "10.0.0.0/24"

  HTTPPort:
    Type: Number

Resources:
  # VPC
  VPC:
    Type: AWS::EC2::VPC
    Properties:
      CidrBlock: !Ref VpcCidrBlock
      EnableDnsSupport: true
      Tags:
        - Key: "Name"
          Value: !Sub "${PJPrefix}-vpc"

  # Internet Gateway
  IGW:
    Type: AWS::EC2::InternetGateway

  # Internet Gateway Attachment
  IGWAttachment:
    Type: AWS::EC2::VPCGatewayAttachment
    Properties:
      VpcId: !Ref VPC
      InternetGatewayId: !Ref IGW

  # VPC Subnet
  VpcSubnet:
    Type: AWS::EC2::Subnet
    Properties:
      AvailabilityZone: !Sub "${AWS::Region}${AvailabilityZone1}"
      VpcId: !Ref VPC
      CidrBlock: !Ref VpcSubnetCidr
      Tags:
        - Key: "Name"
          Value: !Sub "${PJPrefix}-vpcsubnet"

  # Security Group
  ContainerSecurityGroup:
    Type: AWS::EC2::SecurityGroup
    Properties:
      GroupName: !Sub "${PJPrefix}-ServiceSecurityGroup"
      GroupDescription: Allow HTTP.
      VpcId: !Ref VPC
      SecurityGroupIngress:
        - IpProtocol: tcp
          FromPort: !Ref HTTPPort
          ToPort: !Ref HTTPPort
          CidrIp: "0.0.0.0/0"

Outputs:
  VPC:
    Value: !Ref VPC

  VpcSubnet:
    Value: !Ref VpcSubnet

  ContainerSecurityGroup:
    Value: !Ref ContainerSecurityGroup
