AWSTemplateFormatVersion: '2010-09-09'
Description: Spdataservice - WAF Set up.

Parameters:
  Service:
    Type: String
    Default: spdataservice
  environment:
    Type: String
    Default: dev
  envId:
    AllowedValues: ["spds01", "spds02"]
    Type: String
    Default: spds01
  WebACLName:
    Type: String
    Description: Name for the WAF WebACL
    Default: MyWebACL

Resources:
# ##################################################
# ## WAF
# ##################################################
  WAFWebACL:
    Type: 'AWS::WAFv2::WebACL'
    Properties:
      Name: !Ref WebACLName
      Scope: CLOUDFRONT
      DefaultAction:
        Allow: {}
        #Block: {}
      VisibilityConfig:
        SampledRequestsEnabled: true
        CloudWatchMetricsEnabled: true
        MetricName: !Sub bpf-${environment}-${Service}-cloudfront-webacl
      Rules: 
        - Name: !Sub ${environment}-${Service}-cloudfront-webacl-rule
          Action:
              Allow: {}
          Priority: 0
          Statement:
            IPSetReferenceStatement:
              Arn: !GetAtt CloudFrontWafIpSet.Arn
          VisibilityConfig:
            SampledRequestsEnabled: true     
            CloudWatchMetricsEnabled: true       
            MetricName: !Sub ${environment}-${Service}-cloudfront-webacl-rule
      Tags: 
        - Key: Name
          Value: !Sub bpf-${environment}-${Service}-cloudfront-webacl
        - Key: Service
          Value: !Ref Service
        - Key: Environment
          Value: !Ref environment

  CloudFrontWafIpSet:
    Type: AWS::WAFv2::IPSet
    Properties: 
      Addresses: 
        - 1.1.1.1/32
      Description: IP set for Cloudfront
      IPAddressVersion: IPV4
      Name: !Sub ${environment}-${Service}-cloudfront-webacl-ipset
      Scope: CLOUDFRONT
      Tags: 
        - Key: Name
          Value: !Sub ${environment}-${Service}-cloudfront-webacl-ipset
        - Key: Service
          Value: !Ref Service
        - Key: Environment
          Value: !Ref environment

Outputs:
  WebACLIdOutput:
    Description: WebACL ID
    Value: !GetAtt WAFWebACL.Arn
    Export:
      Name: !Sub ${envId}-${environment}-WebACLId
